name: Run Azure Login with OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.28

      - name: Install bun
        run: bun install

      - name: Install cdk8s
        run: bun add cdk8s

      - name: cdk8s synth
        run: bunx cdk8s synth

      - name: Run Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --resource-group insendio_group --name insendio --overwrite-existing

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 1.27.7
        id: install

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s
