name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.28

      - name: Install deps
        run: bun install

      - name: cdk8s synth
        run: bun run synth

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.27.7

      - name: Log generated k8s files
        run: ls -l dist

      - name: Deploy to Kubernetes
        run: kubectl apply -f dist/insendio-*.k8s.yaml
